### ISSUE TITLE
Input change

### ISSUE THREAD

**Issue by quartist** [rogerp67/homebridge-yamaha_mc3#1]
Hi,

plugin works OK. ON/OFF and volume regulation working without problem. But I would like to build automation like:
- when I power on my TV then power on my yamaha and set input to TV.
- when I power off my TV then power off my yamaha. (This working).
- when power on my yamaha and set input to Internet Radio or Bluetooth, power off the TV.
How to change Input via HomeKit app? Maybe it is possible to create many accessories with others input? One yamaha mc3 for TV, one for bluetooth etc.

**Comment by rogerp67** [comment]
Since the Homekit devices only allow characteristics typically for them, like fanspeed and on/off, there are no options left. One option could be a setting in the config, so you are able to connect multiple ones which have different default sources. I will have a look at it. When I am done, I will provide an update.
